### ISSUE TITLE
GRBW Sk6812 white LED doesn't light up

### ISSUE THREAD

**Issue by dertobias** [djcysmic/NeopixelBusFX#20]
recently bought an sk6812GRBW (warm white) strip…
changed the define code to:
`#define GRBW //This is used for SK6812rgbw pixels that have the separate white led in them.`
and everything compiled without an error.

while trying white, or better `nfx all FFFFFF` i found it a bit to blueish and cold so i dimmed a little bit and found out that the white LED on the side doesn't light up at all - instead R, G and B are lit! - shouldn't they be completely off with an RGBW led and "FFFFFF" also tried hue settings but all the same :-(

**Comment by djcysmic** [comment]
For RGBW you have to use 4 colors in hex: rrggbbww
In your case it would be 000000FF to light up only the white channel.
It is not calculated into the RGB color because there are many different stripes with different color temperatures for the white channel (cold, neutral, warm etc.)

Hope this helps ;)

**Comment by dertobias** [comment]
Many THXs! this helps ;)
