### ISSUE TITLE
general question: mqtt enabled? conflicts with neocandle?

### ISSUE THREAD

**Issue by ozett** [djcysmic/NeopixelBusFX#3]
Hi,
i found your plugin, and wanted to try this.
i have Plugin 042 (NeoCandle) sucessful running with self-compiled EspEasyMega Build 20102.

1)
can i send the commands from the readme with MQTT ?
( i do this with neocandle, and maybe all your plugins-commands work the same with mqtt?)

2)
can i have both plugins installed?
or can only one plugin be active/installed for one neopixel-strip?

thanks for a reply,
ozett

(maybe i check the espeasy-forum for some discussion about your plugin?)

**Comment by djcysmic** [comment]
Hello ozett,
the MQTT interface is part of ESP Easy so it should be possible to control this plugin with MQTT.
But I haven't tested it by myself yet - I'm using the FHEM-Interface.

It is also possible to install Neocandle- and NeoPixelBus-Plugin, but you can't use both plugins at the same stripe and the same time, because one plugin reserves the data pin for itself and blocks it for the other plugin.

In the ESPEasy forum there is no thread about this plugin, I think, but in the German FHEM forum there are some more infos:

[https://forum.fhem.de/index.php/topic,73949.0.html](url)

**Comment by ozett** [comment]
very cool, 👍 
it works with MQTT

see example -> https://github.com/djcysmic/NeopixelBusFX/issues/6#issuecomment-433656045
